USE universidad;
SELECT nombre, apellido1, apellido2 FROM persona ORDER BY apellido1, apellido2, nombre ASC;
SELECT nombre, apellido1, apellido2 FROM persona WHERE telefono IS NULL;
SELECT nombre, apellido1, apellido2 FROM persona WHERE fecha_nacimiento BETWEEN '1999-01-01' AND '1999-12-31';
SELECT * FROM persona WHERE tipo = 'profesor' AND telefono IS NULL AND nif LIKE '%K';
SELECT * FROM asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT p.apellido1, p.apellido2, p.nombre, d.nombre AS 'nom departament' FROM persona p JOIN profesor prof ON p.id = prof.id_profesor JOIN departamento d ON d.id = prof.id_departamento ORDER BY apellido1, apellido2, nombre ASC;
SELECT a.nombre, c.anyo_inicio, c.anyo_fin FROM persona p JOIN alumno_se_matricula_asignatura ON alumno_se_matricula_asignatura.id_alumno = p.id JOIN asignatura a ON a.id = alumno_se_matricula_asignatura.id_asignatura JOIN curso_escolar c ON c.id = alumno_se_matricula_asignatura.id_curso_escolar WHERE p.nif = '26902806M';
SELECT DISTINCT d.nombre FROM departamento d JOIN profesor p ON p.id_departamento = d.id JOIN asignatura a ON a.id_profesor = p.id_profesor JOIN grado g ON g.id = a.id_grado WHERE g.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
SELECT DISTINCT p.* FROM persona p JOIN alumno_se_matricula_asignatura ON alumno_se_matricula_asignatura.id_alumno = p.id JOIN curso_escolar c ON c.id = alumno_se_matricula_asignatura.id_curso_escolar WHERE c.anyo_inicio = '2018' AND c.anyo_fin = '2019';
SELECT d.nombre AS 'nom departament', p.apellido1, p.apellido2, p.nombre FROM persona p LEFT JOIN profesor prof ON p.id = prof.id_profesor LEFT JOIN departamento d ON d.id = prof.id_departamento WHERE p.tipo = 'profesor' ORDER BY d.nombre, p.apellido1, p.apellido2, p.nombre ASC;
SELECT p.* FROM persona p LEFT JOIN profesor prof ON p.id = prof.id_profesor WHERE p.tipo = 'profesor' AND prof.id_departamento IS NULL;
SELECT d.* FROM departamento d LEFT JOIN profesor prof ON d.id = prof.id_departamento WHERE prof.id_departamento IS NULL;
SELECT p.* FROM persona p LEFT JOIN profesor prof ON p.id = prof.id_profesor LEFT JOIN asignatura a ON a.id_profesor = prof.id_profesor WHERE p.tipo = 'profesor' AND a.id IS NULL;
SELECT a.* FROM asignatura a LEFT JOIN profesor prof ON prof.id_profesor = a.id_profesor WHERE prof.id_profesor IS NULL;
SELECT DISTINCT d.* FROM departamento d LEFT JOIN profesor prof ON d.id = prof.id_departamento LEFT JOIN asignatura a ON a.id_profesor = prof.id_profesor WHERE a.id IS NULL;
SELECT COUNT(id) FROM persona WHERE tipo = 'alumno';
SELECT COUNT(id) FROM persona WHERE tipo = 'alumno' AND fecha_nacimiento BETWEEN '1999-01-01' AND '1999-12-31';
SELECT d.nombre AS 'nom departament', COUNT(prof.id_profesor) AS 'nombre professors' FROM departamento d JOIN profesor prof ON d.id = prof.id_departamento GROUP BY d.id  ORDER BY COUNT(prof.id_profesor) DESC;
SELECT d.nombre AS 'nom departament', COUNT(prof.id_profesor) AS 'nombre professors' FROM departamento d LEFT JOIN profesor prof ON d.id = prof.id_departamento GROUP BY d.id;
SELECT g.*, COUNT(a.id) AS 'nombre assignatures' FROM grado g LEFT JOIN asignatura a ON a.id_grado = g.id GROUP BY g.id ORDER BY COUNT(a.id) DESC;
SELECT g.*, COUNT(a.id) AS 'nombre assignatures' FROM grado g JOIN asignatura a ON a.id_grado = g.id GROUP BY g.id HAVING COUNT(a.id) > 40;
SELECT g.nombre AS 'nom del grau', a.tipo, SUM(a.creditos) AS 'suma dels crèdits' FROM grado g JOIN asignatura a ON a.id_grado = g.id GROUP BY g.nombre, a.tipo;
SELECT c.anyo_inicio, COUNT(aa.id_alumno) FROM alumno_se_matricula_asignatura aa JOIN curso_escolar c ON c.id = aa.id_curso_escolar GROUP BY c.anyo_inicio;
SELECT p.id, p.nombre, p.apellido1, p.apellido2, COUNT(a.id) AS 'Nombre assignatures' FROM asignatura a RIGHT JOIN profesor prof ON prof.id_profesor = a.id_profesor JOIN persona p ON p.id = prof.id_profesor GROUP BY p.id ORDER BY COUNT(a.id) DESC;
SELECT * FROM persona WHERE tipo = 'alumno' ORDER BY fecha_nacimiento DESC LIMIT 1;
SELECT p.* FROM persona p JOIN profesor prof ON prof.id_profesor = p.id JOIN departamento d ON d.id = prof.id_departamento LEFT JOIN asignatura a ON a.id_profesor = prof.id_profesor WHERE a.id IS NULL;